-- Phase 2 steps 7–11: conflict flagging and local/cloud synchronization.
--
-- §17 requires Forge to detect or flag conflicting knowledge and to preserve
-- both sides until a human resolves it. Automatic resolution stays out of
-- scope. A newly recorded statement that closely resembles an active one is
-- stored `pending_review` with `conflicts_with` pointing at what it resembles,
-- so it lands in the existing review queue instead of silently duplicating.
alter table context_entries add column if not exists conflicts_with uuid
  references context_entries(id) on delete set null;

create index if not exists context_entries_conflicts_with_idx
  on context_entries (conflicts_with);

comment on column context_entries.conflicts_with is
  'Set when this entry was flagged as a possible duplicate/contradiction of another active entry (§17). Never auto-resolved.';

-- Local Context Store replicas (§10). The cloud bank stays authoritative; this
-- only records what each machine has seen so pulls can be incremental and
-- pushes can be reconciled. Deleting a local store loses nothing.
create table if not exists sync_clients (
  clerk_org_id  text not null references organizations(clerk_org_id) on delete cascade,
  client_id     text not null,             -- stable id generated by the local package
  user_id       text not null,
  label         text,                      -- hostname / workspace, for the UI
  created_at    timestamptz not null default now(),
  last_seen_at  timestamptz not null default now(),
  primary key (clerk_org_id, client_id),
  foreign key (clerk_org_id, user_id) references users(clerk_org_id, id) on delete cascade
);

-- Per feature, the newest entry timestamp a client has successfully pulled.
create table if not exists sync_state (
  clerk_org_id  text not null,
  client_id     text not null,
  feature_id    uuid not null references features(id) on delete cascade,
  cursor        timestamptz not null,      -- max(created_at) delivered so far
  entry_count   integer not null default 0,
  updated_at    timestamptz not null default now(),
  primary key (clerk_org_id, client_id, feature_id)
);

alter table sync_clients enable row level security;
alter table sync_state   enable row level security;
